services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - .env.dev
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    depends_on:
      - db
    volumes:
      - ./:/code
    command: sh -c 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    stdin_open: true
    tty: true

volumes:
  postgres_data_dev:
