name: Deploy
on:
  push:
    branches: [ 'master' ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            docker compose -f docker-compose.prod.yml down
            docker ps
            git checkout master
            git pull
            docker compose -f docker-compose.prod.yml up -d --build
            docker ps
